---
title: "Heston Calibration"
output: html_document
---

```{r}
#install.packages("pracma")
library("NMOF")
library("pracma")
```
Approximate SGD
```{r}
SGD <- function(kappa, theta, miu, rho, deltaK, deltaT, deltaM, deltaR, alpha){
  dfdk = (short_opt(c(kappa + deltaK, theta, miu, rho)) - short_opt(c(kappa - deltaK, theta, miu, rho)))/2*deltaK
  dfdt = (short_opt(c(kappa, theta + deltaT, miu, rho)) - short_opt(c(kappa, theta-deltaT, miu, rho)))/2*deltaT
  dfdm = (short_opt(c(kappa, theta, miu+deltaM, rho)) - short_opt(c(kappa, theta, miu-deltaM, rho)))/2*deltaM
  dfdr = (short_opt(c(kappa, theta, miu, rho+ deltaR)) - short_opt(c(kappa , theta, miu, rho -deltaR)))/2*deltaR
  newK = kappa - alpha*dfdk
  newT = theta - alpha*dfdt
  newM = miu - alpha*dfdm
  newR = rho - alpha*dfdr
  return (c(newK, newT, newM, newR))
}
```


See effect of delta
```{r}
kappa <- 0.1
theta <- 0.2
rho <- -0.2
miu <- 0.001
deltas <- seq(0, 0.4,0.0001)
gradient <- rep(0,length(deltas))
for (i in 1:length(deltas)){
  gradient[[i]] <- (short_opt(c(kappa + deltas[[i]], theta, miu, rho)) - short_opt(c(kappa - deltas[[i]], theta, miu, rho)))/2*deltas[[i]]
}

plot(deltas, gradient)

```


SV Monte Carlo Function
```{r}
MSE <- function(vec1, vec2){
  ms <- (vec1-vec2)^2
  return ((sum(ms))^0.5)/length(vec1)
}



```




```{r}
stock <- read.csv("BABA_Stock.csv");
short_mat <- read.csv("BABA_190K_20th7.csv");
long_mat <- read.csv("BABA_190K_21st9.csv")

stock_px <- stock[,3]
shortT_px <- short_mat[,6]
longT_px <- long_mat[,6]


stock_px <- c(na.exclude(stock_px)) [1:27]
shortT_px <- c(na.exclude(shortT_px))[1:27]
longT_px <- c(na.exclude(longT_px)) [1:27]

short_opt <- function(param_vectors){
  a <- param_vectors[[1]]
  theta <- param_vectors[[2]]
  miu <- param_vectors[[3]]
  rho<- param_vectors[[4]]
  kappa <- (a + miu^2)/(2*theta)
  sv_est = rep(0, length(stock_px))
  for (i in 1:length(stock_px)){
    sv_est[[i]] <- callHestoncf(stock_px[[i]], 190, 1/12, 0.02,0,0.04, theta, rho, kappa, miu)
  }
  return (MSE(sv_est, shortT_px))
}

grid_search <- function(kappa, theta, deltaK, deltaT){
  min <- short_opt(c(kappa, theta, deltaK, deltaT))
  minK <- kappa
  minT <- theta
  for(dk in c(-deltaK, 0, deltaK)){
    for (dt in c(-deltaT, 0, deltaT)){
      curr <- short_opt(c(kappa + dk, theta + dt, 0.001, -0.2))
      if (curr<min){
        min <- curr
        minK <- kappa + dk
        minT <- theta + dt
      }
    }
  }
  if (minK == kappa && minT == theta){
    deltaK <- deltaK/2
    deltaT <- deltaT/2
  } 
  return (c(minK, minT,deltaK, deltaT))
}

```


```{r}
grid_search_dummy <- function(kappa, theta, deltaK, deltaT){
  min <- dummy_opt(c(kappa, theta, deltaK, deltaT))
  minK <- kappa
  minT <- theta
  for(dk in c(-deltaK, 0, deltaK)){
    for (dt in c(-deltaT, 0, deltaT)){
      curr <- dummy_opt(c(kappa + dk, theta + dt, 0.001, -0.2))
      if (curr<min){
        min <- curr
        minK <- kappa + dk
        minT <- theta + dt
      }
    }
  }
  if (minK == kappa && minT == theta){
    deltaK <- deltaK/2
    deltaT <- deltaT/2
  } 
  return (c(minK, minT,deltaK, deltaT))
  
}

#Check effectiveness of grid_search 
dummy_opt <- function(param_vectors){
  a <- param_vectors[[1]]
  theta <- param_vectors[[2]]
  miu <- param_vectors[[3]]
  rho<- param_vectors[[4]]
  kappa <- (a + miu^2)/(2*theta)
  sv_est = rep(0, length(stock_px))
  for (i in 1:length(stock_px)){
    sv_est[[i]] <- callHestoncf(stock_px[[i]], 190, 1/12, 0.02,0,0.04, theta, rho, kappa, miu)
  }
  return (MSE(sv_est, shortT_px))
}

kappa <- 0.3
theta <- 0.02
strikes <- c(90,95,100,105,110)
px <- rep(0,length(strikes))
for (i in 1:length(strikes)){
  px[[i]] <- callHestoncf(100, strikes[[i]], 1/12, 0.02,0,0.04, theta, -0.2, kappa, 0.01)
}

oldk <- 0.5
oldt <- 0.4
newk <- 0.3
newt<- 0.4
deltaK <- 0.01
deltaT <- 0.01
new_vecs<-c(2,1)
while (deltaK>0.0001 && deltaT > 0.0001){
  oldk<-newk
  oldt<-newt
  old_vecs <- c(oldk, oldt, oldm, oldr)
  new_vecs <- grid_search(oldk, oldt, deltaK, deltaT)
  newk<- new_vecs[[1]]
  newt <- new_vecs[[2]]
  deltaK <- new_vecs[[3]]
  deltaT <- new_vecs[[4]]
  print(deltaK)
  print(deltaT)
}

print(newk)
print(newt)


```

Calibration code
```{r}
oldk <- 0.3
oldt <- 0.4
newk <- 0.1
newt<- 0.2
deltaK <- 0.01
deltaT <- 0.01
new_vecs<-c(2,1)
while (deltaK>0.0001 && deltaT > 0.0001){
  oldk<-newk
  oldt<-newt
  old_vecs <- c(oldk, oldt, oldm, oldr)
  new_vecs <- grid_search(oldk, oldt, deltaK, deltaT)
  newk<- new_vecs[[1]]
  newt <- new_vecs[[2]]
  deltaK <- new_vecs[[3]]
  deltaT <- new_vecs[[4]]
  print(deltaK)
  print(deltaT)
}

print(newk)
print(newt)
```

