---
title: "Monte_Carlo_Call"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
output:
  pdf_document: default
  html_document: default
---
Initialization
```{r}
init_price <- 50
K <- 50
r<- 0.0175
sigma <- 0.2
T <- 5
M <- 1000
N <- 100
```

Code for Black Scholes and Monte Carlo Pricing
```{r}
BS_V0 <- function(S_0, K, r, sigma, T){
  d1 <- (log(S_0/K) + (r + sigma^2/2)*T)/(sigma * sqrt(T)) 
  d2 <- (log(S_0/K) + (r - sigma^2/2)*T)/(sigma * sqrt(T)) 
  res <- S_0 * pnorm(d1) - K*pnorm(d2) * exp(-r * T)
  return(res)
}

MC_V0 <- function(S_0, K, r, sigma, T, N, M){
  payoff <- 0
  for (i in 1:M){
    s <- S_0
    for (n in 1:N){
      s <- s + r*s*(T/N) + sigma * s * rnorm(1) * sqrt(T/N)
    }
    if (s>K){
      payoff <- payoff + s-K
    } 
  }
  res <- (1 + r * (T/N))^-N * payoff
}

BS_V0(50,50,0.0175,0.02,1)
```

Out of money
```{r}
MC <- rep(0,20)
BS <- rep(0,20)

for (i in 1:20){
  MC[[i]] <- MC_V0(init_price, K+i, r, sigma, T, M, N)
  BS[[i]] <- BS_V0(init_price, K+i, r, sigma, T)
}
print(MC)
print(BS)
plot(c(50:69), MC, main = "plot K = 50,...,70", ylab = "Price", xlab="Strike", type = "l", col = "blue")
lines(50:69, BS, col = "red")
legend("topleft",
       c("MonteCarlo","BlackScholes"),
       fill=c("blue","red"))
```

Vary in the money Options
```{r}
priceMC <- rep(0,20)
priceBS <- rep(0,20)

for (i in 0:19){
priceMC[[i+1]] <- MC_V0(init_price, K-19+i, r, sigma, T, M, N)
priceBS[[i+1]] <- BS_V0(init_price, K-19+i, r, sigma, T)
}
plot(K-rev(c(0:19)), priceMC, main = "Price against Strike", ylab = "Price" , xlab = "Strike", type = "l", col = "blue")
lines(K-rev(c(0:19)), priceBS, col="red")
legend("topleft", c("Monte Carlo", "Black Scholes"), fill=c("blue", "red"))
```



Vary sigma
```{r}
sigmas = seq(0,3,0.1)
priceMC = rep(0, length(sigmas))
priceBS = rep(0, length(sigmas))
for (i in 1:length(sigmas)){
  priceMC[[i]] <- MC_V0(init_price, K, r, sigmas[i], T, M, N)
  priceBS[[i]] <- BS_V0(init_price, K, r, sigmas[i], T)
}
plot(sigmas, priceMC, main = "Price against Sigma", ylab="Price",xlab="Volatility", type="l", col="blue")
lines(sigmas, priceBS, col="red")
legend("topleft", c("Monte Carlo", "Black Scholes"), fill = c("blue","red"))
```



