---
title: "MSFT_SABR_Callibrate"
author: "Novdano"
date: "July 22, 2018"
output: html_document
---


```{r}
library("NMOF")
library(ggplot2)
library("plotly")
```


Parse Data
```{r}
calls <- read.csv("MSFT_Data/MSFT_Call_05312018.csv")
S <- 98.84
N <- dim(calls)[[1]]
curr_date <- as.Date("05/31/2018", "%m/%d/%Y")
print(dim(calls))

```

SABR closed form
```{r}
IV_SABR <- function(f, K, t, alpha, beta, rho, nu){
  first = alpha/((f*K)^((1-beta)/2) *(1 + (((1-beta)^2)/24) *(log(f/K))^2 + ((1-beta^4)/1920)*log(f/K)^4))
  z = (nu/alpha) * ((f*K)^((1-beta)/2)) * log(f/K)
  chi_z = log((sqrt(1-2*rho*z+z^2) + z - rho)/(1-rho))
  last = 1 + (((1-beta)^2/24) * alpha^2/((f*K)^(1-beta)) + (1/4) * ((rho*beta*nu*alpha)/((f*K)^((1-beta)/2))) + ((2-3*rho^2)/24)*nu^2)*t
  return (first * (z/chi_z) * last)
}

BS_V0 <- function(S_0, K, r, sigma, T){
  d1 <- (log(S_0/K) + (r + sigma^2/2)*T)/(sigma * sqrt(T)) 
  d2 <- (log(S_0/K) + (r - sigma^2/2)*T)/(sigma * sqrt(T)) 
  res <- S_0 * pnorm(d1) - K*pnorm(d2) * exp(-r * T)
  return(res)
}
```



MSE Calculation
```{r}
MSE <- function(vec1, vec2){
  ms <- (vec1-vec2)^2
  return ((sum(ms))^0.5)/length(vec1)
}

MSFT_Opt_SABR <- function(params){
  alpha <- params[[1]]
  rho <- params[[2]]
  nu <- params[[3]]
  px_est <- rep(0,N)
  for (i in 1:N){
    r=0.0175
    K <- calls[i,1]
    date <- as.Date(calls[i,2], "%m/%d/%Y")
    mkt_px <- calls[i,5]
    sigma0 <- calls[i,6]
    tau <- as.numeric(date-curr_date)/252
    px_est[[i]] <- BS_V0(S, K, r, IV_SABR(S*exp(r*tau), K, tau, alpha, 1, rho, nu), tau)
  }
  return (MSE(px_est,calls[[5]]))
}
```

```{r}
neighbor_MSFT <- function(param_vectors){
  alpha <- param_vectors[[1]]
  rho <- param_vectors[[2]]
  nu <- param_vectors[[3]]
  sdA <- 0.01
  sdR <- 0.1
  sdN <- 0.1
  newA <- rnorm(1, alpha, sdA)
  newR <- rnorm(1, rho, sdR)
  newN <- rnorm (1, nu, sdN)
  while (newA<0 || newA>1 || newR< -1 || newR>1 || newN<0 || newN>1){
    sdA <- sdA/2
    sdR <- sdR/2
    sdN <- sdN/2
    newA <- rnorm(1, alpha, sdA)
    newR <- rnorm(1, rho, sdR)
    newN <- rnorm (1, nu, sdN)
  }
  return (c(newA, newR, newN))
}

acceptance_probability_MSFT <- function(old_cost, new_cost, T){
  return (exp((old_cost-new_cost)/T))
}


simulated_annealing_SABR_MSFT <- function(param_vectors){
  alpha <- param_vectors[[1]]
  rho <- param_vectors[[2]]
  nu <- param_vectors[[3]]
  sol <- param_vectors
  old_cost <- MSFT_Opt_SABR(c(alpha, rho, nu))
  T <- 1.0
  T_min <- 1e-4
  alpha <- 0.9
  while (T > T_min){
    for (i in 1: 100){
      new_sol <- neighbor_MSFT(sol)
      new_cost <-MSFT_Opt_SABR(new_sol)
      ap = acceptance_probability_MSFT(old_cost, new_cost, T)
      if (ap > runif(1, 0, 1)){
        sol <- new_sol
        old_cost <- new_cost 
      }
    }
    T <- T * alpha
  }
  return (c(sol, old_cost))
}
```


```{r}
simulated_annealing_SABR_MSFT(c(0.1, 0.4, 0.5))
simulated_annealing_SABR_MSFT(c(0.6, -0.2, 0.9))
simulated_annealing_SABR_MSFT(c(0.3, -0.6, 0.3))
```